import { mysqlTable, serial, varchar, timestamp, uniqueIndex, tinyint, date, text, int, json, index } from 'drizzle-orm/mysql-core';
import { relations } from 'drizzle-orm';

export const users = mysqlTable(
  'users',
  {
    id: serial('id').primaryKey(),
    phone: varchar('phone', { length: 32 }).notNull(),
    passwordHash: varchar('password_hash', { length: 255 }).notNull(),
    nickname: varchar('nickname', { length: 64 }),
    avatar: text('avatar'),
    gender: tinyint('gender').default(0),
    birthday: date('birthday'),
    region: varchar('region', { length: 128 }),
    favoriteLists: json('favorite_lists'),
    ratings: json('ratings'),
    status: varchar('status', { length: 16 }).default('normal'),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
);

// NEW: Posts table
export const posts = mysqlTable(
  'posts',
  {
    id: serial('id').primaryKey(),
    userId: int('user_id').notNull(),
    title: varchar('title', { length: 120 }).notNull(),
    content: text('content'),
    coverImageUrl: text('cover_image_url'),
    privacy: varchar('privacy', { length: 16 }).default('public'),
    topic: varchar('topic', { length: 64 }),
    commentsCnt: int('comments_cnt').default(0),
    favoritesCnt: int('favorites_cnt').default(0),
    status: varchar('status', { length: 16 }).default('normal'),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
);

// NEW: Post images table
export const postImages = mysqlTable(
  'post_images',
  {
    id: serial('id').primaryKey(),
    postId: int('post_id').notNull(),
    url: text('url').notNull(),
    thumbnailUrl: text('thumbnail_url'),
    caption: text('caption'),
    sortOrder: int('sort_order').default(0),
    createdAt: timestamp('created_at').notNull().defaultNow(),
  },
);

// NEW: Comments table
export const comments = mysqlTable(
  'comments',
  {
    id: serial('id').primaryKey(),
    postId: int('post_id').notNull(),
    userId: int('user_id').notNull(),
    content: text('content').notNull(),
    parentId: int('parent_id'),
    status: varchar('status', { length: 16 }).default('normal'),
    createdAt: timestamp('created_at').notNull().defaultNow(),
  },
);

// NEW: Favorites table (likes/bookmarks)
export const favorites = mysqlTable(
  'favorites',
  {
    id: serial('id').primaryKey(),
    postId: int('post_id').notNull(),
    userId: int('user_id').notNull(),
    createdAt: timestamp('created_at').notNull().defaultNow(),
  },
  (t) => ({
    uniquePostUser: uniqueIndex('favorites_post_user_unique').on(t.postId, t.userId),
  })
);

// NEW: Comment likes table
export const commentLikes = mysqlTable(
  'comment_likes',
  {
    id: serial('id').primaryKey(),
    commentId: int('comment_id').notNull(),
    userId: int('user_id').notNull(),
    createdAt: timestamp('created_at').notNull().defaultNow(),
  },
  (t) => ({
    uniqueCommentUser: uniqueIndex('comment_likes_comment_user_unique').on(t.commentId, t.userId),
  })
);

 // NEW: Friendships table
export const friendships = mysqlTable(
  'friendships',
  {
    id: serial('id').primaryKey(),
    userId: int('user_id').notNull(),
    friendUserId: int('friend_user_id').notNull(),
    status: varchar('status', { length: 16 }).default('pending'),
    createdAt: timestamp('created_at').notNull().defaultNow(),
  },
);

// NEW: Uploaded files table
export const uploadedFiles = mysqlTable(
  'uploaded_files',
  {
    id: varchar('id', { length: 64 }).primaryKey(), // matches the id generated by upload API
    userId: int('user_id').notNull(),
    url: text('url').notNull(),
    thumbnailUrl: text('thumbnail_url'),
    createdAt: timestamp('created_at').notNull().defaultNow(),
  },
);

// Plans table - 用户计划主表
export const plans = mysqlTable(
  'plans',
  {
    id: serial('id').primaryKey(),
    userId: int('user_id').notNull(),
    name: varchar('name', { length: 120 }).notNull(),
    status: varchar('status', { length: 16 }).default('active'),
    activeTab: int('active_tab').default(0),
    startDate: date('start_date'),
    endDate: date('end_date'),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (t) => ({
    userIdIdx: uniqueIndex('plans_user_id_idx').on(t.userId),
  }),
);

// Transport items table - 计划中的交通项
export const transportItems = mysqlTable(
  'transport_items',
  {
    id: serial('id').primaryKey(),
    planId: int('plan_id').notNull(),
    from: varchar('from', { length: 255 }),
    to: varchar('to', { length: 255 }),
    note: text('note'),
    noteExpanded: tinyint('note_expanded').default(0),
    sortOrder: int('sort_order').default(0),
    startDate: date('start_date'),
    endDate: date('end_date'),
    createdAt: timestamp('created_at').notNull().defaultNow(),
  },
  (t) => ({
    planIdIdx: uniqueIndex('transport_items_plan_id_idx').on(t.planId, t.sortOrder),
  }),
);

// Define relations
export const plansRelations = relations(plans, ({ many }) => ({
  transportItems: many(transportItems),
}));

export const transportItemsRelations = relations(transportItems, ({ one }) => ({
  plan: one(plans, {
    fields: [transportItems.planId],
    references: [plans.id],
  }),
}));

// Admin keys table
export const adminKeys = mysqlTable(
  'admin_keys',
  {
    id: serial('id').primaryKey(),
    keyHash: varchar('key_hash', { length: 255 }).notNull(),
    name: varchar('name', { length: 64 }).notNull(),
    isMaster: tinyint('is_master').default(0),
    isActive: tinyint('is_active').default(1),
    expiresAt: timestamp('expires_at'),
    lastUsedAt: timestamp('last_used_at'),
    createdAt: timestamp('created_at').notNull().defaultNow(),
  },
  (t) => ({
    keyHashIdx: uniqueIndex('admin_keys_key_hash_idx').on(t.keyHash),
  }),
);

// NEW: Markers table (POI)
export const markers = mysqlTable(
  'markers',
  {
    id: serial('id').primaryKey(),
    name: varchar('name', { length: 255 }).notNull(),
    lng: varchar('lng', { length: 20 }),
    lat: varchar('lat', { length: 20 }),
    address: varchar('address', { length: 500 }),
    description: text('description'),
    coverImage: text('cover_image'),
    type: varchar('type', { length: 32 }).default('other'),
    status: tinyint('status').default(1),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
);

// Marker images (multiple images per marker)
export const markerImages = mysqlTable(
  'marker_images',
  {
    id: serial('id').primaryKey(),
    markerId: int('marker_id').notNull(),
    url: text('url').notNull(),
    thumbnailUrl: text('thumbnail_url'),
    caption: text('caption'),
    sortOrder: int('sort_order').default(0),
    createdAt: timestamp('created_at').notNull().defaultNow(),
  },
  (t) => ({
    markerIdIdx: index('marker_images_marker_id_idx').on(t.markerId),
  }),
);

// NEW: Lists table (榜单)
export const lists = mysqlTable(
  'lists',
  {
    id: serial('id').primaryKey(),
    name: varchar('name', { length: 255 }).notNull(),
    coverImage: text('cover_image'),
    description: text('description'),
    position: int('position'), // 位置：在榜单中的排序位置
    intro: text('intro'), // 简介：榜单的介绍文字
    lng: varchar('lng', { length: 20 }),
    lat: varchar('lat', { length: 20 }),
    status: tinyint('status').default(1),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
);

// List group images (multiple images per list)
export const listImages = mysqlTable(
  'list_images',
  {
    id: serial('id').primaryKey(),
    listId: int('list_id').notNull(),
    url: text('url').notNull(),
    thumbnailUrl: text('thumbnail_url'),
    caption: text('caption'),
    sortOrder: int('sort_order').default(0),
    createdAt: timestamp('created_at').notNull().defaultNow(),
  },
  (t) => ({
    listIdIdx: index('list_images_list_id_idx').on(t.listId),
  }),
);

// Embed access logs
export const embedAccessLogs = mysqlTable(
  'embed_access_logs',
  {
    id: serial('id').primaryKey(),
    ip: varchar('ip', { length: 45 }).notNull(),
    action: varchar('action', { length: 32 }).notNull(),
    listId: int('list_id'),
    itemId: int('item_id'),
    userAgent: text('user_agent'),
    createdAt: timestamp('created_at').notNull().defaultNow(),
  },
);

// Ratings table
export const ratings = mysqlTable(
  'ratings',
  {
    id: serial('id').primaryKey(),
    userId: int('user_id').notNull(),
    targetType: varchar('target_type', { length: 32 }).notNull(),
    targetId: int('target_id').notNull(),
    rating: tinyint('rating').notNull(),
    comment: text('comment'),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (t) => ({
    uniqueUserTarget: uniqueIndex('ratings_user_target_unique').on(t.userId, t.targetType, t.targetId),
  })
);

// List items table (榜单项)
export const listItems = mysqlTable(
  'list_items',
  {
    id: serial('id').primaryKey(),
    listId: int('list_id').notNull(),
    title: varchar('title', { length: 255 }).notNull(),
    coverImage: text('cover_image'),
    description: text('description'),
    intro: text('intro'),
    imageUrl: text('image_url'),
    lng: varchar('lng', { length: 20 }),
    lat: varchar('lat', { length: 20 }),
    address: varchar('address', { length: 500 }),
    orderNum: int('order_num').default(0),
    status: tinyint('status').default(1),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
);

// Packing categories table (行李清单分类)
export const packingCategories = mysqlTable(
  'packing_categories',
  {
    id: serial('id').primaryKey(),
    name: varchar('name', { length: 64 }).notNull(),
    orderNum: int('order_num').default(0),
    status: tinyint('status').default(1),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
);

// Packing templates table (行李清单物品模板)
export const packingTemplates = mysqlTable(
  'packing_templates',
  {
    id: serial('id').primaryKey(),
    categoryId: int('category_id').notNull(),
    name: varchar('name', { length: 64 }).notNull(),
    orderNum: int('order_num').default(0),
    status: tinyint('status').default(1),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (t) => ({
    categoryIdIdx: index('packing_templates_category_id_idx').on(t.categoryId),
  }),
);

// Footprints classification
export { footprintGroups, footprintGroupItems } from './schema.footprints';
export { alistConfig } from './schema.alist';

export { storageFiles } from './schema.storage';
export { userFootprintSettings } from './schema.footprintSettings';
