import { mysqlTable, serial, varchar, timestamp, uniqueIndex, tinyint, date, text, int } from 'drizzle-orm/mysql-core';

export const users = mysqlTable(
  'users',
  {
    id: serial('id').primaryKey(),
    phone: varchar('phone', { length: 32 }).notNull(),
    passwordHash: varchar('password_hash', { length: 255 }).notNull(),
    nickname: varchar('nickname', { length: 64 }),
    avatar: text('avatar'),
    gender: tinyint('gender').default(0),
    birthday: date('birthday'),
    region: varchar('region', { length: 128 }),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (t) => ({
    phoneUnique: uniqueIndex('users_phone_unique').on(t.phone),
  }),
);

// NEW: Posts table
export const posts = mysqlTable(
  'posts',
  {
    id: serial('id').primaryKey(),
    userId: int('user_id').notNull(),
    title: varchar('title', { length: 120 }).notNull(),
    content: text('content'),
    coverImageUrl: text('cover_image_url'),
    privacy: varchar('privacy', { length: 16 }).default('public'),
    topic: varchar('topic', { length: 64 }),
    commentsCnt: int('comments_cnt').default(0),
    favoritesCnt: int('favorites_cnt').default(0),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
);

// NEW: Post images table
export const postImages = mysqlTable(
  'post_images',
  {
    id: serial('id').primaryKey(),
    postId: int('post_id').notNull(),
    url: text('url').notNull(),
    thumbnailUrl: text('thumbnail_url'),
    caption: text('caption'),
    sortOrder: int('sort_order').default(0),
    createdAt: timestamp('created_at').notNull().defaultNow(),
  },
);

// NEW: Comments table
export const comments = mysqlTable(
  'comments',
  {
    id: serial('id').primaryKey(),
    postId: int('post_id').notNull(),
    userId: int('user_id').notNull(),
    content: text('content').notNull(),
    createdAt: timestamp('created_at').notNull().defaultNow(),
  },
);

 // NEW: Friendships table
export const friendships = mysqlTable(
  'friendships',
  {
    id: serial('id').primaryKey(),
    userId: int('user_id').notNull(),
    friendUserId: int('friend_user_id').notNull(),
    status: varchar('status', { length: 16 }).default('pending'),
    createdAt: timestamp('created_at').notNull().defaultNow(),
  },
);

// NEW: Uploaded files table
export const uploadedFiles = mysqlTable(
  'uploaded_files',
  {
    id: varchar('id', { length: 64 }).primaryKey(), // matches the id generated by upload API
    userId: int('user_id').notNull(),
    url: text('url').notNull(),
    thumbnailUrl: text('thumbnail_url'),
    createdAt: timestamp('created_at').notNull().defaultNow(),
  },
);
