import type { CSSProperties } from 'react';

/** 浮窗内联样式集中管理，与全局 CSS 解耦 */
export const modalStyles: Record<string, CSSProperties> = {
  /**
   * 单层蒙层：背景 + flex 居中白框同一元素上，`onClick` 用 `target === currentTarget` 仅点空白关闭。
   * （拆 `backdrop` + `pointer-events:none` 父级在部分浏览器下会穿透命中，表现为「点白框也关」。）
   */
  overlay: {
    position: 'fixed',
    inset: 0,
    zIndex: 120,
    isolation: 'isolate',
    background: 'rgba(17, 24, 39, 0.42)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '24px 20px',
    boxSizing: 'border-box',
    overflow: 'auto',
  },
  closeFloat: {
    position: 'fixed',
    top: 18,
    left: 18,
    zIndex: 130,
    width: 32,
    height: 32,
    borderRadius: '50%',
    border: '1px solid rgba(255,255,255,0.4)',
    background: 'rgba(0,0,0,0.35)',
    color: '#fff',
    fontSize: 20,
    lineHeight: 1,
    cursor: 'pointer',
  },
  frame: {
    position: 'relative',
    zIndex: 1,
    flexShrink: 0,
    width: 'min(1120px, 90vw)',
    height: 'min(760px, 86vh)',
    maxWidth: '100%',
    background: '#fff',
    borderRadius: 12,
    boxShadow: '0 24px 48px rgba(17,24,39,0.24)',
    overflow: 'hidden',
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 58%) minmax(0, 42%)',
    columnGap: 0,
    alignItems: 'stretch',
  },
  /** 左栏：主图 + 缩略图（flex 分配高度，避免 nested grid 下 1fr 塌陷导致主图不可见） */
  mediaPanel: {
    minHeight: 0,
    minWidth: 0,
    height: '100%',
    alignSelf: 'stretch',
    display: 'flex',
    flexDirection: 'column',
    background: '#fff',
    overflow: 'hidden',
  },
  /** 父级在 mediaPanel flex 内占满剩余高度后，内部绝对定位 img 才能稳定铺满（避免 img 百分比高度在 flex 下为 0） */
  mainImageStage: {
    flex: '1 1 0%',
    minHeight: 200,
    minWidth: 0,
    width: '100%',
    position: 'relative',
    background: '#f3f4f6',
    overflow: 'hidden',
    cursor: 'pointer',
  },
  mainImage: {
    position: 'absolute',
    inset: 0,
    width: '100%',
    height: '100%',
    objectFit: 'contain',
    objectPosition: 'center',
    display: 'block',
    /** 命中落在 stage 上，保证全屏下滑动 / capture 与单击退出稳定 */
    pointerEvents: 'none',
  },
  thumbPanel: {
    position: 'relative',
    height: 90,
    minHeight: 90,
    flexShrink: 0,
    background: '#fff',
    borderTop: '1px solid var(--color-border)',
  },
  thumbRail: {
    height: '100%',
    overflowX: 'auto',
    overflowY: 'hidden',
    padding: '8px 12px',
    boxSizing: 'border-box',
    WebkitOverflowScrolling: 'touch',
    touchAction: 'pan-x',
    cursor: 'grab',
    userSelect: 'none',
  },
  thumbTrack: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'nowrap',
    alignItems: 'center',
    gap: 8,
    width: 'max-content',
    minWidth: 'max-content',
    height: '100%',
    paddingRight: 24,
  },
  thumbBtn: {
    border: '2px solid var(--color-border)',
    borderRadius: 8,
    padding: 0,
    overflow: 'hidden',
    background: '#fff',
    cursor: 'pointer',
    flex: '0 0 auto',
    width: 72,
    height: 72,
  },
  thumbImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    display: 'block',
    pointerEvents: 'none',
  },
  infoPanel: {
    minHeight: 0,
    minWidth: 0,
    display: 'grid',
    gridTemplateRows: 'auto auto auto 1fr auto auto',
    background: '#fff',
    borderLeft: '1px solid var(--color-border)',
  },
  authorRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '14px 16px 10px',
  },
  authorLeft: { display: 'flex', alignItems: 'center', gap: 10 },
  authorAvatar: { width: 36, height: 36, borderRadius: '50%', objectFit: 'cover' },
  /** 地图入口：图标按钮（右上角） */
  mapIconBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 40,
    height: 40,
    flexShrink: 0,
    border: '1px solid var(--color-border)',
    borderRadius: 10,
    background: '#fff',
    color: '#2563eb',
    padding: 0,
    cursor: 'pointer',
    boxSizing: 'border-box',
  },
  contentBlock: { padding: '0 16px 12px', borderBottom: '1px solid var(--color-border)' },
  title: { display: 'block', marginBottom: 8, fontSize: 20, lineHeight: 1.25 },
  content: { margin: 0, color: '#374151', lineHeight: 1.55, fontSize: 14 },
  tags: { marginTop: 10, color: '#2563eb', fontSize: 14 },
  commentCount: { padding: '10px 16px 8px', color: 'var(--color-text-muted)', fontSize: 13 },
  commentList: { minHeight: 0, overflow: 'auto', padding: '0 16px 8px', display: 'grid', gap: 6 },
  commentItem: { display: 'grid', gridTemplateColumns: '28px 1fr', gap: 8, padding: '8px 0' },
  commentAvatar: { width: 28, height: 28, borderRadius: '50%', objectFit: 'cover', marginTop: 2 },
  commentName: {
    fontSize: 12,
    color: '#111827',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  commentTime: { color: 'var(--color-text-muted)', fontSize: 11 },
  commentText: { margin: 0, fontSize: 13, lineHeight: 1.35, color: '#374151' },
  commentMeta: { color: 'var(--color-text-muted)' },
  interactionBar: {
    display: 'flex',
    alignItems: 'center',
    gap: 16,
    padding: '10px 16px',
    borderTop: '1px solid var(--color-border)',
    borderBottom: '1px solid var(--color-border)',
    color: '#374151',
    fontSize: 14,
  },
  planBtn: {
    marginLeft: 'auto',
    border: 'none',
    background: 'var(--color-primary)',
    color: '#fff',
    borderRadius: 999,
    padding: '6px 12px',
    cursor: 'pointer',
  },
  inputRow: { display: 'grid', gridTemplateColumns: '1fr auto', gap: 8, padding: '10px 16px', background: '#fff' },
  input: {
    border: '1px solid var(--color-border)',
    borderRadius: 999,
    padding: '8px 12px',
    outline: 'none',
  },
  sendBtn: {
    border: 'none',
    background: 'var(--color-primary)',
    color: '#fff',
    borderRadius: 8,
    padding: '8px 12px',
    cursor: 'pointer',
  },
};

